name: j-quest-compose

services:

  j-quest-mysql:
    image: mysql:8.0.44-debian
    container_name: j-quest-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_quest

    networks:
      - j-quest-net

    volumes:
      - ../quest-init/quest-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - jquest_db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  j-quest-boot:
    image: ajc/quest:boot
    container_name: j-quest-boot

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://j-quest-mysql:3306/projet_quest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      j-quest-mysql:
        condition: service_healthy

    ports:
      - "9020:8080"

    networks:
      - j-quest-net

  j-quest-angular:
    image: ajc/quest:angular
    container_name: j-quest-angular

    depends_on:
      - j-quest-boot

    ports:
      - "9000:80"

    networks:
      - j-quest-net

# ---- ATTENTION ----
# Ces sections doivent Ãªtre EN DEHORS de "services:"
# -------------------

volumes:
  jquest_db_data:
    name: jquest-db-data

networks:
  j-quest-net:
    name: j-quest-net